# Generated by Django 5.0 on 2023-12-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_rename_author_comment_user_rename_author_tweet_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='slug',
        ),
    ]
