# Generated by Django 5.0 on 2023-12-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_tweet_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='following',
        ),
    ]
