# Generated by Django 5.0 on 2023-12-07 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_rename_is_following_follow_follow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follow',
        ),
        migrations.AddField(
            model_name='follow',
            name='follow',
            field=models.ManyToManyField(related_name='is_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
