# Generated by Django 5.0 on 2023-12-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_remove_follow_follow_follow_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={},
        ),
    ]
