# Generated by Django 5.0 on 2023-12-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_alter_tweet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-date']},
        ),
    ]
